// leave off @2x/@3x
export const images = {
  logo: require("../Images/ir.png"),
  clearLogo: require("../Images/top_logo.png"),
  launch: require("../Images/launch-icon.png"),
  ready: require("../Images/your-app.png"),
  ignite: require("../Images/ignite_logo.png"),
  igniteClear: require("../Images/ignite-logo-transparent.png"),
  tileBg: require("../Images/tile_bg.png"),
  background: require("../Images/BG.png"),
  buttonBackground: require("../Images/button-bg.png"),
  api: require("../Images/Icons/icon-api-testing.png"),
  components: require("../Images/Icons/icon-components.png"),
  deviceInfo: require("../Images/Icons/icon-device-information.png"),
  faq: require("../Images/Icons/faq-icon.png"),
  home: require("../Images/Icons/icon-home.png"),
  theme: require("../Images/Icons/icon-theme.png"),
  usageExamples: require("../Images/Icons/icon-usage-examples.png"),
  chevronRight: require("../Images/Icons/chevron-right.png"),
  hamburger: require("../Images/Icons/hamburger.png"),
  backButton: require("../Images/Icons/back-button.png"),
  closeButton: require("../Images/Icons/close-button.png"),

  logoIcon: require("../Images/MaskGroup(17).png"),
  helpIcon: require("../Images/MaskGroup(11).png"),
  isiKolamIcon: require("../Images/Icons/Group322.png"),
  karantinaIcon: require("../Images/Icons/Group323.png"),
  mulaiFlokIcon: require("../Images/Icons/Group324.png"),
  tebarBenihIcon: require("../Images/Icons/Group325.png"),
  pemberianPakanIcon: require("../Images/Icons/Group326.png"),
  ukurKadarPhIcon: require("../Images/Icons/Group327.png"),
  ukurKadarNitritIcon: require("../Images/Icons/Group328.png"),
  ukurKadarNitratIcon: require("../Images/Icons/Group329.png"),
  ukurKadarDoIcon: require("../Images/Icons/Group330.png"),
  ukurKadarAmoniakIcon: require("../Images/Icons/Group331.png"),
  laporKematianIcon: require("../Images/Icons/Group332.png"),
  tambahFlokSusulanIcon: require("../Images/Icons/Group333.png"),
  laporanIcon: require("../Images/Icons/Group334.png"),
  ukurKadarFlokIcon: require("../Images/Icons/Group335.png"),
  pemindahanBibitIcon: require("../Images/Icons/Group336.png"),
  kurasKolamIcon: require("../Images/Icons/Group337.png"),
  kematianKarantinaIcon: require("../Images/Icons/Group338.png"),
  laporanBobotIcon: require("../Images/Icons/Group339.png"),
  laporanDowntimeIcon: require("../Images/Icons/Group340.png"),
  laporanCuacaIcon: require("../Images/Icons/Group341.png"),
  lainnyaIcon: require("../Images/Icons/Group17.png"),
  sample: require("../Images/image2.png"),
  noneImage: require("../Images/Group309.png"),
  sample2: require("../Images/image6.png"),
  pp: require("../Images/man.png"),
  // pp: require('../Images/Ellipse68(1).png'),
  profilBg: require("../Images/Vector(1).png"),
  profileIcon: require("../Images/user.png"),
  akunIcon: require("../Images/shield-lock-line-icon.png"),
  notifIcon: require("../Images/notification.png"),
  helpIcon2: require("../Images/find-problem-icon.png"),
  logoutIcon: require("../Images/logout-line-icon.png"),
  dateIcon: require("../Images/Icons/date.png"),
  smileIcon: require("../Images/Icons/Maskgroup16.png"),
  svgtes: require("../Images/tes.svg"),
  // iconWarning: require('../Images/red-alert-icon.png'),
}
